{% set name = "happi" %}
{% set version = "1.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 14b0173019cf066f15aff92e462762a71ba9be13dfc1cb70548195907a76115d

build:
  noarch: python
  number: 1
  entry_points:
    - happi = happi.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jinja2
    - prettytable
    - simplejson
    - coloredlogs
    - ipython
    - entrypoints

test:
  imports:
    - happi
  commands:
    - happi --help

about:
  home: https://github.com/pcdshub/happi
  dev_url: https://github.com/pcdshub/happi
  doc_url: https://pcdshub.github.io/happi
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: Heuristic Access to Positions of Photon Instruments

extra:
  recipe-maintainers:
    - klauer
    - zrylettc
    - ZLLentz
