{% set name = "happi" %}
{% set version = "2.6.1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: efc0468702aacda8108e63d755b414d51fd039b0f4765668e8cab6e7a3128a96

build:
  noarch: python
  number: 0
  entry_points:
    - happi = happi.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - click
    - coloredlogs
    - entrypoints
    - jinja2
    - platformdirs
    - prettytable
    - simplejson
  run_constrained:
    - psdm_qs_cli >=0.3.1
    - pymongo >=4.0.2

test:
  requires:
    - python {{ python_min }}
  imports:
    - happi
  commands:
    - happi --help

about:
  home: https://github.com/pcdshub/happi
  dev_url: https://github.com/pcdshub/happi
  doc_url: https://pcdshub.github.io/happi
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: Heuristic Access to Positions of Photon Instruments

extra:
  recipe-maintainers:
    - conda-forge/pcdsdevices
