{% set name = "happi" %}
{% set version = "1.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pcdshub/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 3a6831a7d0330c77e3e0a9e5ce8de12b85e1d2a02109c1b9e9e0800309dca412

build:
  noarch: python
  number: 0
  entry_points:
    - happi = happi.cli:main

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - jinja2
    - prettytable
    - simplejson
    - coloredlogs
    - ipython
    - entrypoints

test:
  imports:
    - happi
  commands:
    - happi --help

about:
  home: https://github.com/pcdshub/happi
  dev_url: https://github.com/pcdshub/happi
  doc_url: https://pcdshub.github.io/happi
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  license_file: LICENSE.md
  summary: Heuristic Access to Positions of Photon Instruments

extra:
  recipe-maintainers:
    - hhslepicka
    - klauer
    - ZLLentz
